// Feature Service: Events & Opinion Markets Data Engine
export const CATEGORIES = [
  { id: "all", label: "All Indices", icon: "grid" },
  { id: "indices", label: "Benchmark Indices", icon: "trending-up" },
  { id: "sectoral", label: "Sectoral Indices", icon: "pie-chart" },
  { id: "macro", label: "Volatility & Macro", icon: "pulse" },
];

export const EVENTS_DATA = [
  {
    id: "nifty-50",
    title: "NIFTY 50",
    category: "indices",
    question: "Will NIFTY 50 close ABOVE 24,200.00 at 3:30 PM IST today?",
    description: "Settlement will be based on the official NSE closing index value published at 15:30 IST.",
    status: "OPEN",
    currentPrice: "24,187.65",
    spotNumeric: 24187.65,
    defaultTargetPrice: 24250,
    quickIncrements: [-100, -50, 50, 100, 250],
    priceStep: 50,
    change: "+0.84%",
    isPositive: true,
    yesPrice: 6.2,
    noPrice: 3.8,
    yesProbability: 62,
    noProbability: 38,
    totalVolume: "₹24.8 Lakhs",
    totalVolumeUsdt: "33,780 USDT",
    prizePoolInr: "₹1,00,000",
    prizePoolUsdt: "13,620.27",
    entryInr: "₹199",
    entryUsdt: "2.71 USDT",
    players: 8431,
    closesIn: "02h 45m 12s",
    fillPercent: 84,
    fillColor: "#00C987",
    settlementSource: "National Stock Exchange (NSE India)",
    settlementDate: "Today, 03:30 PM IST",
    chartHistory: [
      { time: "09:15", yes: 4.5, no: 5.5 },
      { time: "10:00", yes: 5.0, no: 5.0 },
      { time: "11:00", yes: 5.8, no: 4.2 },
      { time: "12:00", yes: 5.2, no: 4.8 },
      { time: "13:00", yes: 6.0, no: 4.0 },
      { time: "14:00", yes: 6.5, no: 3.5 },
      { time: "Live", yes: 6.2, no: 3.8 },
    ],
    orderBook: {
      yes: [
        { price: 6.2, qty: 1420 },
        { price: 6.1, qty: 3850 },
        { price: 6.0, qty: 8900 },
        { price: 5.9, qty: 12400 },
      ],
      no: [
        { price: 3.8, qty: 1150 },
        { price: 3.9, qty: 4200 },
        { price: 4.0, qty: 7800 },
        { price: 4.1, qty: 15300 },
      ],
    },
    rules: [
      "The market resolves YES if NSE Nifty 50 closing price is strictly greater than 24,200.00.",
      "The official closing value from NSE (published around 3:45 PM IST) will be final.",
      "In case of market disruption or delayed close, settlement will wait until official NSE data is released.",
      "Trading halts at 3:25 PM IST.",
    ],
  },
  {
    id: "bank-nifty",
    title: "BANK NIFTY",
    category: "indices",
    question: "Will BANK NIFTY touch 52,000 during today's intraday session?",
    description: "Resolves YES instantly if Bank Nifty intraday high reaches >= 52,000 at any second before 3:30 PM.",
    status: "OPEN",
    currentPrice: "51,843.25",
    spotNumeric: 51843.25,
    defaultTargetPrice: 52000,
    quickIncrements: [-250, -100, 100, 250, 500],
    priceStep: 100,
    change: "+1.12%",
    isPositive: true,
    yesPrice: 7.1,
    noPrice: 2.9,
    yesProbability: 71,
    noProbability: 29,
    totalVolume: "₹52.1 Lakhs",
    totalVolumeUsdt: "70,960 USDT",
    prizePoolInr: "₹5,00,000",
    prizePoolUsdt: "68,101.40",
    entryInr: "₹99",
    entryUsdt: "1.35 USDT",
    players: 12410,
    closesIn: "04h 55m 00s",
    fillPercent: 91,
    fillColor: "#00C987",
    settlementSource: "National Stock Exchange (NSE India)",
    settlementDate: "Today, 03:30 PM IST",
    chartHistory: [
      { time: "09:15", yes: 5.0, no: 5.0 },
      { time: "10:15", yes: 5.9, no: 4.1 },
      { time: "11:30", yes: 6.4, no: 3.6 },
      { time: "13:00", yes: 6.8, no: 3.2 },
      { time: "Live", yes: 7.1, no: 2.9 },
    ],
    orderBook: {
      yes: [
        { price: 7.1, qty: 5600 },
        { price: 7.0, qty: 9800 },
        { price: 6.9, qty: 15400 },
      ],
      no: [
        { price: 2.9, qty: 4200 },
        { price: 3.0, qty: 8100 },
        { price: 3.1, qty: 11000 },
      ],
    },
    rules: [
      "Immediate resolution if Intraday High is >= 52,000.",
      "If not reached by 3:30 PM IST, resolves NO.",
    ],
  },
  {
    id: "sensex",
    title: "SENSEX",
    category: "indices",
    question: "Will BSE SENSEX remain above 79,500 at today's market close?",
    description: "Official settlement based on BSE closing price published today.",
    status: "• LIVE",
    currentPrice: "79,432.18",
    spotNumeric: 79432.18,
    defaultTargetPrice: 79500,
    quickIncrements: [-250, -100, 100, 250, 500],
    priceStep: 100,
    change: "-0.31%",
    isPositive: false,
    yesPrice: 3.4,
    noPrice: 6.6,
    yesProbability: 34,
    noProbability: 66,
    totalVolume: "₹38.2 Lakhs",
    totalVolumeUsdt: "52,030 USDT",
    prizePoolInr: "₹2,50,000",
    prizePoolUsdt: "34,050.67",
    entryInr: "₹299",
    entryUsdt: "4.07 USDT",
    players: 5902,
    closesIn: "00h 42m 19s",
    fillPercent: 74,
    fillColor: "#EF4444",
    topHighlight: "#EF4444",
    settlementSource: "Bombay Stock Exchange (BSE India)",
    settlementDate: "Today, 03:30 PM IST",
    chartHistory: [
      { time: "09:15", yes: 6.0, no: 4.0 },
      { time: "10:30", yes: 5.2, no: 4.8 },
      { time: "11:45", yes: 4.5, no: 5.5 },
      { time: "13:00", yes: 3.8, no: 6.2 },
      { time: "14:15", yes: 3.2, no: 6.8 },
      { time: "Live", yes: 3.4, no: 6.6 },
    ],
    orderBook: {
      yes: [
        { price: 3.4, qty: 2300 },
        { price: 3.3, qty: 5400 },
        { price: 3.2, qty: 9100 },
      ],
      no: [
        { price: 6.6, qty: 3100 },
        { price: 6.7, qty: 6200 },
        { price: 6.8, qty: 14000 },
      ],
    },
    rules: [
      "The market resolves YES if SENSEX closing price is >= 79,500.00.",
      "Resolves NO if closing price is < 79,500.00.",
      "Official BSE closing rate is the sole authority.",
    ],
  },
  {
    id: "fin-nifty",
    title: "FINNIFTY",
    category: "sectoral",
    question: "Will NIFTY FINANCIAL SERVICES cross 23,750 before weekly close?",
    description: "Settles according to official NSE FINNIFTY index closing levels.",
    status: "OPEN",
    currentPrice: "23,650.40",
    spotNumeric: 23650.40,
    defaultTargetPrice: 23750,
    quickIncrements: [-100, -50, 50, 100, 200],
    priceStep: 50,
    change: "+0.62%",
    isPositive: true,
    yesPrice: 5.5,
    noPrice: 4.5,
    yesProbability: 55,
    noProbability: 45,
    totalVolume: "₹19.4 Lakhs",
    totalVolumeUsdt: "26,420 USDT",
    prizePoolInr: "₹80,000",
    prizePoolUsdt: "10,896.20",
    entryInr: "₹49",
    entryUsdt: "0.67 USDT",
    players: 3820,
    closesIn: "03h 15m",
    fillPercent: 70,
    fillColor: "#00C987",
    settlementSource: "NSE Financial Index",
    settlementDate: "Today, 03:30 PM IST",
    chartHistory: [
      { time: "09:15", yes: 4.8, no: 5.2 },
      { time: "11:00", yes: 5.1, no: 4.9 },
      { time: "13:00", yes: 5.4, no: 4.6 },
      { time: "Live", yes: 5.5, no: 4.5 },
    ],
    orderBook: {
      yes: [
        { price: 5.5, qty: 3200 },
        { price: 5.4, qty: 6100 },
      ],
      no: [
        { price: 4.5, qty: 2800 },
        { price: 4.6, qty: 5400 },
      ],
    },
    rules: [
      "Resolves YES if FINNIFTY spot price touches or closes >= 23,750.00.",
    ],
  },
  {
    id: "nifty-it",
    title: "NIFTY IT",
    category: "sectoral",
    question: "Will NIFTY IT sustain above 41,500 today?",
    description: "NSE Sectoral IT benchmark index tracking top Indian tech firms.",
    status: "OPEN",
    currentPrice: "41,250.80",
    spotNumeric: 41250.80,
    defaultTargetPrice: 41500,
    quickIncrements: [-200, -100, 100, 200, 400],
    priceStep: 100,
    change: "+1.35%",
    isPositive: true,
    yesPrice: 6.4,
    noPrice: 3.6,
    yesProbability: 64,
    noProbability: 36,
    totalVolume: "₹31.5 Lakhs",
    totalVolumeUsdt: "42,900 USDT",
    prizePoolInr: "₹1,50,000",
    prizePoolUsdt: "20,430.40",
    entryInr: "₹149",
    entryUsdt: "2.03 USDT",
    players: 4890,
    closesIn: "02h 10m",
    fillPercent: 82,
    fillColor: "#00C987",
    settlementSource: "NSE IT Sector Index",
    settlementDate: "Today, 03:30 PM IST",
    chartHistory: [
      { time: "09:15", yes: 5.2, no: 4.8 },
      { time: "11:30", yes: 6.0, no: 4.0 },
      { time: "Live", yes: 6.4, no: 3.6 },
    ],
    orderBook: {
      yes: [{ price: 6.4, qty: 4500 }],
      no: [{ price: 3.6, qty: 3800 }],
    },
    rules: [
      "Settles based on official NSE IT index closing rate.",
    ],
  },
  {
    id: "midcp-nifty",
    title: "MIDCP NIFTY",
    category: "indices",
    question: "Will NIFTY MIDCAP SELECT gain more than +1.0% by market close?",
    description: "Settlement based on percentage change from previous day's official close.",
    status: "OPEN",
    currentPrice: "12,980.15",
    spotNumeric: 12980.15,
    defaultTargetPrice: 13050,
    quickIncrements: [-50, -25, 25, 50, 100],
    priceStep: 25,
    change: "+0.95%",
    isPositive: true,
    yesPrice: 5.9,
    noPrice: 4.1,
    yesProbability: 59,
    noProbability: 41,
    totalVolume: "₹14.2 Lakhs",
    totalVolumeUsdt: "19,340 USDT",
    prizePoolInr: "₹60,000",
    prizePoolUsdt: "8,172.15",
    entryInr: "₹49",
    entryUsdt: "0.67 USDT",
    players: 2940,
    closesIn: "03h 05m",
    fillPercent: 65,
    fillColor: "#00C987",
    settlementSource: "NSE Midcap Index",
    settlementDate: "Today, 03:30 PM IST",
    chartHistory: [
      { time: "09:15", yes: 4.7, no: 5.3 },
      { time: "12:00", yes: 5.5, no: 4.5 },
      { time: "Live", yes: 5.9, no: 4.1 },
    ],
    orderBook: {
      yes: [{ price: 5.9, qty: 2200 }],
      no: [{ price: 4.1, qty: 1900 }],
    },
    rules: [
      "Resolves YES if net daily gain >= 1.00%.",
    ],
  },
];

let userTrades = [
  {
    tradeId: "TRD-89211",
    eventId: "nifty-50",
    title: "NIFTY 50",
    tradeMode: "PRICE_TARGET",
    targetPrice: 24250,
    multiplier: 2.85,
    delta: 62.35,
    question: "Target Price Prediction: 24,250.00",
    option: "PRICE_TARGET",
    quantity: 50,
    buyPrice: 10,
    currentPrice: 10,
    investedAmount: 500,
    currentValue: 500,
    pnl: 0,
    pnlPercent: 0,
    potentialPayout: 1425,
    status: "ACTIVE",
    timestamp: "Today, 11:24 AM",
  },
  {
    tradeId: "TRD-77340",
    eventId: "bank-nifty",
    title: "BANK NIFTY",
    tradeMode: "DIRECTIONAL",
    question: "Will BANK NIFTY touch 52,000 during today's intraday session?",
    option: "YES",
    quantity: 100,
    buyPrice: 6.0,
    currentPrice: 7.1,
    investedAmount: 600,
    currentValue: 710,
    pnl: 110,
    pnlPercent: 18.33,
    potentialPayout: 1000,
    status: "ACTIVE",
    timestamp: "Today, 09:45 AM",
  },
  {
    tradeId: "TRD-65109",
    eventId: "sensex",
    title: "SENSEX",
    tradeMode: "DIRECTIONAL",
    question: "Will BSE SENSEX close above 79,200 yesterday?",
    option: "NO",
    quantity: 30,
    buyPrice: 4.0,
    currentPrice: 10.0,
    investedAmount: 120,
    currentValue: 300,
    pnl: 180,
    pnlPercent: 150.0,
    potentialPayout: 300,
    status: "SETTLED_WON",
    timestamp: "Yesterday, 02:15 PM",
  },
];

export function fetchEventById(id) {
  return EVENTS_DATA.find((e) => e.id === id) || EVENTS_DATA[0];
}

export function fetchEvents(categoryId = "all") {
  if (categoryId === "all") return EVENTS_DATA;
  return EVENTS_DATA.filter((e) => e.category === categoryId);
}

export function fetchUserTrades() {
  return [...userTrades];
}

export function submitTradeOrder({
  eventId,
  tradeMode = "PRICE_TARGET",
  targetPrice = null,
  multiplier = 2.0,
  delta = 0,
  option,
  quantity,
  pricePerUnit,
  investedAmount,
  potentialPayout,
}) {
  const event = fetchEventById(eventId);
  const investment = investedAmount || Math.round(quantity * pricePerUnit * 10) / 10;
  const payout = potentialPayout || Math.round(investment * multiplier * 10) / 10;

  const newTrade = {
    tradeId: `TRD-${Math.floor(10000 + Math.random() * 90000)}`,
    eventId,
    title: event.title,
    tradeMode,
    targetPrice,
    multiplier,
    delta,
    question:
      tradeMode === "PRICE_TARGET"
        ? `Target Price: ₹${Number(targetPrice).toLocaleString()}`
        : event.question,
    option: tradeMode === "PRICE_TARGET" ? "TARGET" : option,
    quantity,
    buyPrice: pricePerUnit,
    currentPrice: pricePerUnit,
    investedAmount: investment,
    currentValue: investment,
    pnl: 0,
    pnlPercent: 0,
    potentialPayout: payout,
    status: "ACTIVE",
    timestamp: "Just now",
  };

  userTrades = [newTrade, ...userTrades];
  return newTrade;
}

export function executeExitTrade(tradeId) {
  userTrades = userTrades.map((t) =>
    t.tradeId === tradeId ? { ...t, status: "EXITED" } : t
  );
  return true;
}
